### ISSUE TITLE
How to run the code for the first time using CPU only?

### ISSUE THREAD

**Issue by watchernyu** [xingdi-eric-yuan/MatchLSTM-PyTorch#6]
Hi! Thank you for the implementation! I'm trying to run the train.py file on my laptop, and found an error about using NVIDIA GPU, my computer doesn't have a NVIDIA GPU so I wonder if there is a flag we can use to use CPU only? Many thanks!

**Comment by watchernyu** [comment]
Sorry for the dumb question! I found the setting in config files!

**Comment by xingdi-eric-yuan** [comment]
yeah, sorry for the delay, exactly, you can disable cuda in the config file.
