### ISSUE TITLE
Squad json to txt code?

### ISSUE THREAD

**Issue by watchernyu** [xingdi-eric-yuan/MatchLSTM-PyTorch#7]
Hi! Thanks for your last reply! I wonder if you still have the code used to produce the txt files in tokenized_squad_v1.1.2 folder? We are trying to run some expanded Squad dataset that (in original json format) on the implementation so it would be really helpful if you can upload that to your directory!

**Comment by xingdi-eric-yuan** [comment]
I do have that but sorry I can't release that because it is owned by Microsoft. Basically, it tokenizes storys/questions using NLTK work tokenizer.

**Comment by watchernyu** [comment]
No problem! Thank you so much for the information! I will try doing it with NLTK!
