### ISSUE TITLE
epoch count to get the result ?

### ISSUE THREAD

**Issue by mickyyu96** [xingdi-eric-yuan/MatchLSTM-PyTorch#8]
Hello, how much epoch needed to get the result like in README ?
I try running first epoch and it only get:
INFO - epoch=0, valid nll loss=6.04093, valid f1=0.23862, valid em=0.14327, lr=0.002000

Am i in a right path ?

**Comment by xingdi-eric-yuan** [comment]
Hi as the figure shows, most configs converge after 20+ epochs. your 1st epoch result looks fine.

**Comment by mickyyu96** [comment]
Oh thanks. I forgot about the graph in README. Thanks for the reply
